<a href="https://colab.research.google.com/github/schneeball1230/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [5]:
def phasor(amp, sr, dur, freq):
  t = np.arange(1, sr*dur + 1)/sr
  theta = t*2*np.pi*freq
  s = np.sin(theta)
  return s, theta, t

In [12]:
phasor(1, 10000, 0.5, 200.0)

(array([ 1.25333234e-01,  2.48689887e-01,  3.68124553e-01, ...,
        -2.48689887e-01, -1.25333234e-01,  3.92877345e-15]),
 array([1.25663706e-01, 2.51327412e-01, 3.76991118e-01, ...,
        6.28067203e+02, 6.28192867e+02, 6.28318531e+02]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 4.998e-01, 4.999e-01,
        5.000e-01]))

In [10]:
def phasor_audio(amp, sr, dur, freq):
  t = np.arange(1, sr*dur + 1)/sr
  theta = t*2*np.pi*freq
  s = np.sin(theta)
  return ipd.Audio(s, rate=sr)

In [11]:
phasor_audio(1, 10000, 0.5, 200.0)